/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReadRouteImport } from './routes/read'
import { Route as ReadIdRouteImport } from './routes/read.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadRoute = ReadRouteImport.update({
  id: '/read',
  path: '/read',
  getParentRoute: () => rootRouteImport,
} as any)
const ReadIdRoute = ReadIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReadRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/read': typeof ReadRouteWithChildren
  '/read/$id': typeof ReadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/read': typeof ReadRouteWithChildren
  '/read/$id': typeof ReadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/read': typeof ReadRouteWithChildren
  '/read/$id': typeof ReadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/read' | '/read/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/read' | '/read/$id'
  id: '__root__' | '/' | '/read' | '/read/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ReadRoute: typeof ReadRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read': {
      id: '/read'
      path: '/read'
      fullPath: '/read'
      preLoaderRoute: typeof ReadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/read/$id': {
      id: '/read/$id'
      path: '/$id'
      fullPath: '/read/$id'
      preLoaderRoute: typeof ReadIdRouteImport
      parentRoute: typeof ReadRoute
    }
  }
}

interface ReadRouteChildren {
  ReadIdRoute: typeof ReadIdRoute
}

const ReadRouteChildren: ReadRouteChildren = {
  ReadIdRoute: ReadIdRoute,
}

const ReadRouteWithChildren = ReadRoute._addFileChildren(ReadRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ReadRoute: ReadRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
