export const PRAYERS: { night: number; week: number; text: string; reference: string }[] = [
  { night: 1, week: 1, text: "God, help us see clearly — not to assign blame, just to notice where the distance actually lives.", reference: "Psalm 139:23–24" },
  { night: 2, week: 1, text: "Show us the moment connection quietly became logistics, and give us the patience to notice it without shame.", reference: "Proverbs 4:23" },
  { night: 3, week: 1, text: "Slow us down enough to actually hear each other's small, easy-to-miss bids for attention.", reference: "James 1:19" },
  { night: 4, week: 1, text: "We bring You what we're really longing for, even the parts we haven't said out loud to each other yet.", reference: "Psalm 62:8" },
  { night: 5, week: 1, text: "Where we've told ourselves a hopeless story about this marriage, help us see the truer, gentler one.", reference: "Isaiah 43:18–19" },
  { night: 6, week: 1, text: "Give us the courage for one small turn toward each other this week, however small it feels.", reference: "1 Thessalonians 5:11" },
  { night: 7, week: 1, text: "Thank You for whatever we were willing to notice this week, even the uncomfortable parts.", reference: "Psalm 100:4–5" },
  { night: 8, week: 2, text: "Where fear has kept us quiet, replace it with the steadiness to speak honestly.", reference: "2 Timothy 1:7" },
  { night: 9, week: 2, text: "Make us quick to repair and slow to escalate, even when we're tired or hurt.", reference: "Matthew 5:9" },
  { night: 10, week: 2, text: "Help us find the softer truth underneath our sharpest complaints.", reference: "Proverbs 20:5" },
  { night: 11, week: 2, text: "Let the words we practice this week actually land as gentle, even under pressure.", reference: "Proverbs 16:24" },
  { night: 12, week: 2, text: "Season our speech with grace tonight, especially in the small, ordinary friction.", reference: "Colossians 4:6" },
  { night: 13, week: 2, text: "Cast out whatever fear is keeping either of us from being fully honest.", reference: "1 John 4:18" },
  { night: 14, week: 2, text: "Thank You for whatever honest words got said this week — help us keep speaking truth in love.", reference: "Ephesians 4:15" },
  { night: 15, week: 3, text: "Remind us that we're stronger noticing and rebuilding this together than either of us could alone.", reference: "Ecclesiastes 4:9–10" },
  { night: 16, week: 3, text: "Teach us to number these small, ordinary days rightly, instead of waiting for a dramatic one.", reference: "Psalm 90:12" },
  { night: 17, week: 3, text: "Let our yes be yes this week — help us keep the small promises we make to each other.", reference: "Matthew 5:37" },
  { night: 18, week: 3, text: "Thank You for the small deposits we made into each other this week, even the ones that went unnoticed.", reference: "1 Thessalonians 5:18" },
  { night: 19, week: 3, text: "Give us the patience to keep this small habit going, even after the novelty wears off.", reference: "Galatians 6:9" },
  { night: 20, week: 3, text: "Help us be genuinely devoted to each other in this one small, ordinary ritual tonight.", reference: "Romans 12:10" },
  { night: 21, week: 3, text: "We commit this rebuilding to You, trusting it more than our own uncertain feelings about how it's going.", reference: "Proverbs 3:5–6" },
  { night: 22, week: 4, text: "Thank You for whatever has actually shifted this month, however small it looks from the outside.", reference: "Psalm 126:3" },
  { night: 23, week: 4, text: "Thank You that Your mercy toward us — and the mercy we owe each other — is new again tomorrow morning.", reference: "Lamentations 3:22–23" },
  { night: 24, week: 4, text: "As we write to each other tonight, help our words be true, specific, and kind.", reference: "Song of Solomon 8:6" },
  { night: 25, week: 4, text: "Be the third strand holding what the two of us alone couldn't hold as well.", reference: "Ecclesiastes 4:12" },
  { night: 26, week: 4, text: "Whatever one word describes this month, thank You for the chance to keep choosing better words going forward.", reference: "Proverbs 18:21" },
  { night: 27, week: 4, text: "Thank You for carrying the good work You started in this marriage this month, even in its unfinished shape.", reference: "Philippians 1:6" },
  { night: 28, week: 4, text: "Help us forgive tonight — each other, and ourselves — the way we've been forgiven.", reference: "Colossians 3:13" },
  { night: 29, week: 4, text: "Tomorrow we choose again. Tonight, prepare our hearts to mean it.", reference: "Joshua 24:15" },
  { night: 30, week: 4, text: "Wherever this marriage goes next, we go together — thank You for thirty days that brought us back to that choice.", reference: "Ruth 1:16–17" },
];